# Generated by Django 5.1.3 on 2026-05-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_shopactionrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreviewimage',
            name='variant_image',
        ),
        migrations.AddField(
            model_name='productreviewimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_trusted_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('rejected', 'Rejected'), ('active', 'Active'), ('out_of_stock', 'Out of Stock'), ('inactive', 'Inactive'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='draft', max_length=20),
        ),
    ]
